### ISSUE TITLE
Add more documentation

### ISSUE THREAD

**Issue by dsafa** [dsafa/CSDeskBand#22]
As it is nearing v1, it would be good to add more documentation on usage of the available features

**Comment by brian9206** [comment]
I wonder if there is any option to allow only one deskband instance. For now, if you go to right click taskbar > Toolbar > [your deskband name] multiple times, you can have multiple deskband instance on your taskbar.

**Comment by dsafa** [comment]
Is this winforms or wpf? I know wpf has this issue.

**Comment by brian9206** [comment]
It is wpf. It is exactly same issue that i encountered

**Comment by dsafa** [comment]
Fixed with #24

**Comment by dsafa** [comment]
Wiki [added](https://github.com/dsafa/CSDeskBand/wiki)

**Comment by dsafa** [comment]
Version 2.0.0 #31  has documentation included in nuget packages and has been updated
