### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by KoalaBear84** [dsafa/CSDeskBand#33]
I've used the Sample.Win and Sample.Wpf project to test if it works. Installation went fine, but I cannot select it. Also tried it with a new GUID and Name.

Using Visual Studio 2017 and Windows 10 Version 1803 64-bit, tested with both Pro and Enterprise. Also tested with "Any CPU", "x86" and "x64" (last one gives an error that it is not a valid .NET executable).

- Tested both through elevated Developer Command Prompt and a bat file run from the directory.
- Tested both with Debug and Release mode.
- Tested both with "regasm" and GAC methods.

Bat-file:
```
@setlocal enableextensions
@cd /d "%~dp0"
C:\Windows\Microsoft.NET\Framework\v4.0.30319\regasm.exe /tlb /codebase Sample.Win.dll
pause
```

Result:
```
Microsoft .NET Framework Assembly Registration Utility version 4.7.3056.0
for Microsoft .NET Framework version 4.7.3056.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Succesfully registered deskband `Sample Winforms Deskband` - GUID: {5731fc61-8530-404c-86c1-86ccb8738d06}
Request to show deskband.
Types registered successfully
```

What can I do? Can we debug or test this, or are there any known issues?

Other deskbands like from Networx works fine.

**Comment by KoalaBear84** [comment]
The best issues are the ones that 'fix' themselves. Now I know what you mean with the 32/64 bit part!

Working bat-file:
```
@echo OFF
title Install DeskBand
@echo ON
@setlocal enableextensions
@cd /d "%~dp0"
if defined %PROGRAMFILES(x86)% (
   %SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\regasm.exe /nologo /codebase "Sample.Win.dll"
) else (
   %SystemRoot%\Microsoft.NET\Framework\v4.0.30319\regasm.exe /nologo /codebase "Sample.Win.dll"
)
pause
```

It does not automatically show it, but it does install succesfully!

Could you please update documentation with the part? Or even include this bat file with the automatic 64 bit distinction?

The Developer Command Prompt also does not fix this problem.

**Comment by dsafa** [comment]
Thanks, I'll update the documentation and include the script and examples. I'll also update the part about the developer command prompt/
