### ISSUE TITLE
Left berth by default

### ISSUE THREAD

**Issue by xyfll7** [dsafa/CSDeskBand#44]
in the newest version :
Left berth by default  how to right default？
![image](https://user-images.githubusercontent.com/28172140/58810317-497dd600-8650-11e9-84e9-5f023ddd5983.png)
Default Vertical Topping how to Vertical centering？

**Comment by xyfll7** [comment]
like this in the old version ：
![image](https://user-images.githubusercontent.com/28172140/58810543-b7c29880-8650-11e9-8e6c-07de88995ce9.png)

**Comment by dsafa** [comment]
You'll have to center it in your application or if you set a maximum height with `Options.MaxHorizontalHeight`, windows will center it for you.

**Comment by darkguy2008** [comment]
> You'll have to center it in your application or if you set a maximum height with `Options.MaxHorizontalHeight`, windows will center it for you.

What about the horizontal position though? my deskband appears duplicated as it's at the left AND right sides of the taskbar
