### ISSUE TITLE
Anyone using this in WinForms successfully?

### ISSUE THREAD

**Issue by obelixA** [dsafa/CSDeskBand#57]
all examples I saw were WPF. Did anyone use this in a WinForms project?
#56 is my open issue for WinForms
If someone has a running example for WinForms would be very helpful.
Even the demo WinForms project is not working...

**Comment by srwi** [comment]
It seems to work for me:
![image](https://user-images.githubusercontent.com/17520641/106748264-473dfd00-6625-11eb-8560-480fa2800997.png)
[WindowsFormsApp1.zip](https://github.com/dsafa/CSDeskBand/files/5918475/WindowsFormsApp1.zip)

I have never used WinForms though, so really can't help you any further than this.

**Comment by obelixA** [comment]
HA! thanks a lot!
I saw that we have the same source for using - but your demo works. So there must be another issue.
And it was the GUID of the project. Somehow my registry has some entries scrambled with this GUID. I created another one, and voila - my band can be selected for displaying in the taskbar.
Now I can focus on my other tasks, completing the tools...
